config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get '/closet',        to: 'clothes#index', as: 'closet'
  post '/outfits',      to: 'outfit_selection_rules#select_outfit'
  get '/signup',        to: 'users#new',           as: 'signup'
  get '/login',         to: 'sessions#new',        as: 'login'
  post '/login',        to: 'sessions#create',     as: 'create_login'
  delete '/logout',     to: 'sessions#destroy',    as: 'logout'
  get '/deside',        to: 'static_pages#deside', as: 'deside'
  post '/deside',       to: 'clothes#update_deside', as: 'deside_push'
  get '/home',          to: redirect('/')

  resources :users,       only: %i[new create show edit update destroy]
  resources :clothes,     only: %i[index new create show edit update update_deside destroy]
  resources :cloth_types, only: %i[index new create destroy]
  resources :outfit_selection_rules, as: 'rules', path: 'rules',
                                     only: %i[index show new create destroy]
  resources :outfit_logs, only: %i[index new create show]

  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_login, only: %i[home deside]

  def home
    @user = current_user
  end

  def deside; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/deside.html.erb
<% provide(:title, "home") %>
<%= render 'layouts/flash_messages' %>

<h1>Have a nice day!</h1>
<p>最後に着た日付が更新されました</p>

<div>
  <%= image_tag "sites/halloween_nekomajo.png", alt: "cat" %>
</div>

<div>
  <%= back_link_to(root_path) %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "home") %>
<%= render 'layouts/flash_messages' %>

<p>ようこそ、<strong><%= link_to @user.name, user_path(@user) %></strong> さん。</p>

<h1>トップページ</h1>
<p>最高気温、最低気温を入力して「服を選ぶ」ボタンをクリックしてください。</p>

<%= form_with( url: outfits_path, 
              method: :post,
              html: { class: "form-container" }) do |form| %>
  <ul>
    <li>
      <%= form.label :max_temperature, '最高気温', style: 'color: red;' %>
      <%= form.number_field :max_temperature, value: flash[:max_temperature] %>
    </li>

    <li>
      <%= form.label :min_temperature, '最低気温', style: 'color: blue;' %>
      <%= form.number_field :min_temperature, value: flash[:min_temperature] %>
    </li>
    <li>
      <%= form.submit '服を選ぶ' %>
    </li>
  </ul>
<% end %>

<% if session[:selected_clothes_ids].present? %>
  <div style="display: flex; flex-wrap: wrap;">
    <% Cloth.where(id: session[:selected_clothes_ids]).each do |cloth| %>
      <div style="margin: 10px;">
        <%= image_tag cloth.image, style: 'max-width: 200px; max-height: 200px;' if cloth.image.attached? %>
      </div>
    <% end %>
  </div>
  <% else if session[:outfit_selected] %>
    <div style="margin: 10px;">
      <%= image_tag("seeds/no_image_square.png", style: 'max-width: 200px; max-height: 200px;') %>
    </div>
  <% end%>
<% end %>

<% if session[:outfit_selected] %>
  <%= form_with url: deside_push_path, method: :post do %>
    <%= hidden_field_tag :selected_clothes_ids, session[:selected_clothes_ids].join(",") %>
    <%= button_tag(type: "submit", class: "deside-button") do %>
      <%= image_tag("sites/pop_kettei.png", alt: "決定", style: "max-width: 150px;") %>
    <% end %>
  <% end %>
  <% session.delete(:outfit_selected) %>
  <% session.delete(:selected_clothes_ids) %>
<% end %>

<div class="closet-link-container">
  <ul>
    <li>▼服を管理する▼</li>
    <li>
      <%= link_to image_tag("sites/closet.png", class:"image-closet"), closet_path %>
    </li>
  </ul>
</div>

<div class="edit-link">
  <%= link_to "●過去の服装ログを見る", outfit_logs_path %>
</div>

<div class="edit-link">
  <%= link_to "●服の選択ロジックを管理する", rules_path %>
</div>

<div>
  <%= button_to "ログアウト", logout_path, :method=> :delete %>
</div>