config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get '/closet',        to: 'clothes#index', as: 'closet'
  post '/outfits',      to: 'outfit_selection_rules#select_outfit'
  get '/signup',        to: 'users#new',           as: 'signup'
  get '/login',         to: 'sessions#new',        as: 'login'
  post '/login',        to: 'sessions#create',     as: 'create_login'
  delete '/logout',     to: 'sessions#destroy',    as: 'logout'
  get '/deside',        to: 'static_pages#deside', as: 'deside'
  post '/deside',       to: 'clothes#update_deside', as: 'deside_push'
  get '/home',          to: redirect('/')

  resources :users,       only: %i[new create show edit update destroy]
  resources :clothes,     only: %i[index new create show edit update update_deside destroy]
  resources :cloth_types, only: %i[index new create destroy]
  resources :outfit_selection_rules, as: 'rules', path: 'rules',
                                     only: %i[index show new create destroy]
  resources :outfit_logs, only: %i[index new create show]

  root 'static_pages#home'
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :require_login, only: %i[index new create show edit update update_deside destroy]
  before_action :set_cloth, only: %i[show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :cloth_not_found

  def index
    @clothes = if params[:types].present?
                 current_user.clothes.where(cloth_type_id: params[:types])
               else
                 Cloth.none
               end
  end

  def show; end

  def new
    @cloth = Cloth.new
  end

  def edit; end

  def create
    @cloth = Cloth.new(cloth_params)
    @cloth.user_id = current_user.id
    @cloth.last_worn_on = Date.parse('2000-01-01')
    if @cloth.save
      redirect_with_notice(I18n.t('flash.clothes.create_success'), new_cloth_url)
    else
      render_with_alert(I18n.t('flash.clothes.create_failure'), :new)
    end
  end

  def update
    if @cloth.update(cloth_params)
      redirect_with_notice(I18n.t('flash.clothes.update_success'), cloth_url(@cloth))
    else
      render_with_alert(I18n.t('flash.clothes.update_failure'), :edit)
    end
  end

  def update_deside
    return unless params[:selected_clothes_ids].present?

    selected_clothes_ids = params[:selected_clothes_ids].split(',')
    Cloth.update_last_worn(selected_clothes_ids)
    OutfitLog.create_outfit_log(current_user, selected_clothes_ids)
    redirect_to deside_url
  end

  def destroy
    @cloth.soft_delete
    redirect_with_notice(I18n.t('flash.clothes.destroy_success'), closet_url)
  end

  private

  def set_cloth
    @cloth = Cloth.find(params[:id])
  end

  def cloth_params
    params.require(:cloth).permit(:name, :description, :cloth_type_id, :image)
  end

  def cloth_not_found
    redirect_with_alert(I18n.t('flash.clothes.not_found'), clothes_url)
  end
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/views/clothes/edit.html.erb
<% provide(:title, "edit closs") %>
<%= render 'layouts/flash_messages' %>
<%= javascript_include_tag 'preview_cloth_image' %>

<h1>服の編集</h1>

<% if @cloth.image.attached? %>
  <div id="existing-image">
    <%= image_tag @cloth.image, style: "max-width:400px;" %>
  </div>
<% end %>

<div id="image-preview" style="display:none;">
  <img src="" class="cloth-image" style="max-width: 400px" />
</div>

<%= form_with(model: @cloth,
              url: cloth_path(@cloth),
              local: true,
              html: { class: "form-container" }) do |form| %>
  <ul>
    <li>
      <%= form.label :image, "画像" %>
      <%= form.file_field :image %>
    <li>
      <%= form.label :description, "説明" %>
      <%= form.text_area :description %>
    </li>
    <li>
      <%= form.label :last_worn_on, "最後に着た日" %>
      <%= form.date_select :last_worn_on, start_year: 2000, end_year: Date.today.year %>
    </li>
    <li>
      <%= form.label :cloth_type_id, '服の種類' %>
      <%= form.collection_select :cloth_type_id, ClothType.all, :id, :name,
          { prompt: '-----' }, { class: "select-type" } %>
    </li>
    <li>
      <%= form.submit '更新' %>
    </li>
  </ul>
<% end %>

<div>
  <%= back_link_to(cloth_path(@cloth)) %>
</div>

app/views/clothes/index.html.erb
<% provide(:title, "Closet") %>
<%= javascript_include_tag 'show_clothes' %>
<%= render 'layouts/flash_messages' %>

<h1>クローゼット(衣服管理ページ)</h1>
<p>服を登録したり、登録した服を表示することができます。</p>
<p>服の画像をクリックすると、詳細画面を表示できます。</p>

<div class="closet-link">
  <%= link_to "●服を追加する", new_cloth_path %>
</div>

<div class="closet-link">
  <%= link_to "●服の分類を確認する", cloth_types_path %>
</div>

<%= form_with(url: clothes_path, 
              method: :get,
              html: { class: "checkbox-container" }) do %> 
  <% ClothType.all.each_with_index do |type, index| %>
    <div class="checkbox-item">
      <%= check_box_tag "types[]", type.id, class: "cloth-type-checkbox" %>
      <%= label_tag "types_#{type.id}", type.name, class: "cloth-type-label" %>
    </div>
    <%= '<br>'.html_safe if (index + 1) % 5 == 0 %> <!-- 5つごとに改行 -->
  <% end %>
  <div class="check-button">
    <%= submit_tag "表示", class:"cloth-filter-button" %>
    <%= button_tag 'すべて選択', type: 'button', id: 'select-all', class: "check-all-button" %>
    <%= button_tag 'チェックを外す', type: 'button', id: 'deselect-all', class: "check-all-button" %>
  </div>
<% end %>

<% @clothes.each do |cloth| %>
  <% if cloth.image.attached? %>
    <%=link_to (image_tag cloth.image, width: "200", height: "200"), cloth_path(cloth) %>
  <% end %>
<% end %>

<div>
  <%= back_link_to(root_path) %>
</div>

app/views/clothes/new.html.erb
<% provide(:title, "Add cloth") %>
<%= render 'layouts/flash_messages' %>

<h1>服の登録</h1>

<%= javascript_include_tag 'preview_cloth_image' %>

<div id="image-preview" style="display:none;">
  <img src="" class="cloth-image" style="max-width: 500px; max-height: 500px;" />
</div>

<%= form_with(model: @cloth,  
              local: true,
              html: { class: "form-container" }) do |form| %>

    <ul> 
      <li>
        <%= form.label :image, '画像アップロード', class:"cloth-add" %>
        <%= form.file_field :image, class:"image-upload", accept: 'image/jpeg,image/gif,image/png' %>
      </li>
      <li>
        <%= form.label :cloth_type_id, '服の種類', class:"cloth-add" %>
        <%= form.collection_select :cloth_type_id, ClothType.all, :id, :name,
            { prompt: '選択してください' }, { class: "select-type" } %>
      </li>
      <li>
        <%= form.label :description, '説明', class:"cloth-add" %>
        <%= form.text_area :description, class:"add-cloth-description" %>
      </li>
      <li>
        <%= form.submit '登録する' %>
      </li>
    </ul>
<% end %>

<div>
  <%= back_link_to(closet_path) %>
</div>

app/views/clothes/show.html.erb
<% provide(:title, "Detail") %>
<%= render 'layouts/flash_messages' %>

<h1><%= @cloth.description %></h1>

<p>最後に着た日：<%= @cloth.last_worn_on %></p>
<p>分類：<%= @cloth.cloth_type.name %></p>

<div class="edit-link">
  <%= link_to "●編集", edit_cloth_path(@cloth) %>
</div>

<div>
  <%= back_link_to(closet_path) %>
</div>

<%= image_tag @cloth.image, class:"image-cloth-detail" if @cloth.image.attached? %>

<div>
  <%= general_delete_button("服を削除する", cloth_path(@cloth)) %>
</div>