config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get '/closet',        to: 'clothes#index', as: 'closet'
  post '/outfits',      to: 'outfit_selection_rules#select_outfit'
  get '/signup',        to: 'users#new',           as: 'signup'
  get '/login',         to: 'sessions#new',        as: 'login'
  post '/login',        to: 'sessions#create',     as: 'create_login'
  delete '/logout',     to: 'sessions#destroy',    as: 'logout'
  get '/deside',        to: 'static_pages#deside', as: 'deside'
  post '/deside',       to: 'clothes#update_deside', as: 'deside_push'
  get '/home',          to: redirect('/')

  resources :users,       only: %i[new create show edit update destroy]
  resources :clothes,     only: %i[index new create show edit update update_deside destroy]
  resources :cloth_types, only: %i[index new create destroy]
  resources :outfit_selection_rules, as: 'rules', path: 'rules',
                                     only: %i[index show new create destroy]
  resources :outfit_logs, only: %i[index new create show]

  root 'static_pages#home'
end

app/models/outfit_selection_rule.rb
# == Schema Information
#
# Table name: outfit_selection_rules
#
#  id                          :bigint           not null, primary key
#  description                 :text(65535)
#  max_temperature_lower_bound :float(24)
#  max_temperature_upper_bound :float(24)
#  min_temperature_lower_bound :float(24)
#  min_temperature_upper_bound :float(24)
#  name                        :string(255)      not null
#  priority                    :integer          not null
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#
# Indexes
#
#  index_outfit_selection_rules_on_name  (name) UNIQUE
#
class OutfitSelectionRule < ApplicationRecord
  DEFAULT_PRIORITY = 1

  has_many :cloth_group_selections, dependent: :destroy
  has_many :cloth_groups, through: :cloth_group_selections

  validates :name,     presence: true, uniqueness: true
  validates :priority, presence: true

  def destroyable?
    name != 'default'
  end
end

app/controllers/outfit_selection_rules_controller.rb
class OutfitSelectionRulesController < ApplicationController
  before_action :require_login, only: %i[index new create show select_outfit destroy select_outfit]
  before_action :set_cloth_groups, only: %i[new create]
  rescue_from ActiveRecord::RecordNotFound, with: :rule_not_found

  def index
    @outfit_selection_rules = OutfitSelectionRule.all
  end

  def show
    @outfit_selection_rule = OutfitSelectionRule.includes(:cloth_groups).find(params[:id])
  end

  def new
    @outfit_selection_rule = OutfitSelectionRule.new
  end

  def create
    @outfit_selection_rule = OutfitSelectionRule.new(outfit_selection_rule_params.except(:cloth_group_selections))

    ActiveRecord::Base.transaction do
      @outfit_selection_rule.save!
      process_cloth_group_selections(@outfit_selection_rule,
                                     params[:outfit_selection_rule][:cloth_group_selections] || {})
    end

    redirect_with_notice(I18n.t('flash.outfit_selection_rules.create_success'), rules_url)
  rescue ActiveRecord::RecordInvalid
    render_with_alert(I18n.t('flash.outfit_selection_rules.create_failure'), :new)
  end

  def destroy
    @outfit_selection_rule = OutfitSelectionRule.includes(:cloth_groups).find(params[:id])
    if @outfit_selection_rule.destroyable?
      @outfit_selection_rule.destroy
      redirect_with_notice(I18n.t('flash.outfit_selection_rules.destroy_success'), rules_url)
    else
      redirect_with_alert(I18n.t('flash.outfit_selection_rules.destroy_failure'), rules_url)
    end
  end

  def select_outfit
    max_temperature = params[:max_temperature]
    min_temperature = params[:min_temperature]
    flash[:max_temperature] = max_temperature
    flash[:min_temperature] = min_temperature

    unless valid_number?(max_temperature) && valid_number?(min_temperature)
      redirect_with_alert(I18n.t('flash.outfit_selection_rules.invalid_number'), root_url)
      return
    end

    if min_temperature > max_temperature
      redirect_with_alert(I18n.t('flash.outfit_selection_rules.min_over_max'), root_url)
      return
    end

    outfit_selector = OutfitSelector.new(current_user)
    selected_clothes_ids = outfit_selector.select_outfit(max_temperature, min_temperature)
    if selected_clothes_ids
      session[:selected_clothes_ids] = selected_clothes_ids
      session[:outfit_selected] = true
      redirect_to root_url
    else
      redirect_with_alert(I18n.t('flash.outfit_selection_rules.select_failure'), root_url)
    end
  end

  private

  def outfit_selection_rule_params
    params.require(:outfit_selection_rule).permit(:name, :description, :priority,
                                                  :min_temperature_lower_bound, :min_temperature_upper_bound,
                                                  :max_temperature_lower_bound, :max_temperature_upper_bound,
                                                  cloth_group_selections: {})
  end

  def process_cloth_group_selections(rule, selections_params)
    selections_params.each do |cloth_group_id, selection_count|
      next unless selection_count.to_i.positive?

      ClothGroupSelection.create!(
        outfit_selection_rule_id: rule.id,
        cloth_group_id:,
        selection_count:
      )
    end
  end

  def set_cloth_groups
    @cloth_groups = ClothGroup.all
  end

  def valid_number?(str)
    true if Float(str)
  rescue StandardError
    false
  end

  def rule_not_found
    redirect_with_alert(I18n.t('flash.outfit_selection_rules.not_found'), root_url)
  end
end

app/helpers/outfit_selection_rules_helper.rb
module OutfitSelectionRulesHelper
end

app/views/outfit_selection_rules/index.html.erb
<% provide(:title, "rules") %>
<%= render 'layouts/flash_messages' %>

<h1>ロジック一覧</h1>
<p>気温の条件のマッチしたルールのうち、優先度が高い(値が小さい)条件で選択します</p>

<%= link_to "●ロジックを追加する", new_rule_path %>

<% no_limit_text = '制限なし' %>

<table class="rules-view">
  <thead>
    <tr>
      <th>名前</th>
      <th>説明</th>
      <th>優先度</th>
      <th>最低気温の最低値</th>
      <th>最低気温の最高値</th>
      <th>最高気温の最低値</th>
      <th>最高気温の最高値</th>
    </tr>
  </thead>
  <tbody>
    <% @outfit_selection_rules.each do |rule| %>
      <tr>
        <td><%= link_to rule.name, rule_path(rule) %></td>
        <td><%= rule.description %></td>
        <td><%= rule.priority %></td>
        <td><%= rule.min_temperature_lower_bound || no_limit_text %></td>
        <td><%= rule.min_temperature_upper_bound || no_limit_text %></td>
        <td><%= rule.max_temperature_lower_bound || no_limit_text %></td>
        <td><%= rule.max_temperature_upper_bound || no_limit_text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= back_link_to(root_path) %>
</div>

app/views/outfit_selection_rules/new.html.erb
<% provide(:title, "add rule") %>
<%= render 'layouts/flash_messages' %>

<h1>ロジックを追加する</h1>
<p>・ルール名は必須です。気温を設定しないと上限／下限なしになります。</p>

<%= form_with(model: @outfit_selection_rule, 
              local: true,
              url: rules_path,
              html: { class: "form-container" }) do |form| %>

  <ul>
    <li>
      <%= form.label :name, "ルール名" %>
      <%= form.text_field :name %>
    </li>
    <li>
      <%= form.label :description, "説明" %>
      <%= form.text_area :description %>
    </li>
    <li>
      <%= form.label :priority, "優先度" %>
      <%= form.number_field :priority, value: OutfitSelectionRule::DEFAULT_PRIORITY %>
    </li>
    <li>
      <%= form.label :min_temperature_range, "最低気温" %>
      <%= form.number_field :min_temperature_lower_bound %>度～
      <%= form.number_field :min_temperature_upper_bound %>度
    </li>
    <li>
      <%= form.label :max_temperature_range, "最高気温" %>
      <%= form.number_field :max_temperature_lower_bound %>度～
      <%= form.number_field :max_temperature_upper_bound %>度
    </li>
    <% @cloth_groups.each do |cloth_group| %>
      <li>
        <%= form.label "cloth_group_selections_#{cloth_group.id}", cloth_group.name %>
        <%= number_field_tag "outfit_selection_rule[cloth_group_selections][#{cloth_group.id}]", nil, value:ClothGroup::DEFAULT_SELECT_NUMBER %>枚
      </li>
    <% end %>
    <li>
      <%= form.submit "登録" %>
    </li>
  </ul>
<% end %>

<div>
  <%= back_link_to(rules_path) %>
</div>

app/views/outfit_selection_rules/select_outfit.erb
<h1>仮データだよ</h1>

app/views/outfit_selection_rules/show.html.erb
<% provide(:title, "rule") %>
<h1>ルール<%= @outfit_selection_rule.id %> : <%= @outfit_selection_rule.name %></h1>

<% no_limit_text = '制限なし' %>

<table>
  <tr>
    <th>説明</th>
    <td><%= @outfit_selection_rule.description %></td>
  </tr>
  <tr>
    <th>優先度</th>
    <td><%= @outfit_selection_rule.priority %></td>
  </tr>
  <tr>
    <th>最低気温の最低値</th>
    <td><%= @outfit_selection_rule.min_temperature_lower_bound || no_limit_text %></td>
  </tr>
  <tr>
    <th>最低気温の最高値</th>
    <td><%= @outfit_selection_rule.min_temperature_upper_bound || no_limit_text %></td>
  </tr>
  <tr>
    <th>最高気温の最低値</th>
    <td><%= @outfit_selection_rule.max_temperature_lower_bound || no_limit_text %></td>
  </tr>
  <tr>
    <th>最高気温の最高値</th>
    <td><%= @outfit_selection_rule.max_temperature_upper_bound || no_limit_text %></td>
  </tr>
  <% @outfit_selection_rule.cloth_group_selections.each do |selection| %>
  <tr>
    <th><%= selection.cloth_group.name %></th>
    <td><%= selection.selection_count %>枚</td>
  <% end %>
  </tr>
</table>

<div>
  <%= back_link_to(rules_path) %>
</div>

<div>
  <%= general_delete_button("このルールを削除する", rule_path(@outfit_selection_rule)) %>
  <p>※ルール名が"default"のルールは削除することができません</p>
</div>