config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get '/closet',        to: 'clothes#index', as: 'closet'
  post '/outfits',      to: 'outfit_selection_rules#select_outfit'
  get '/signup',        to: 'users#new',           as: 'signup'
  get '/login',         to: 'sessions#new',        as: 'login'
  post '/login',        to: 'sessions#create',     as: 'create_login'
  delete '/logout',     to: 'sessions#destroy',    as: 'logout'
  get '/deside',        to: 'static_pages#deside', as: 'deside'
  post '/deside',       to: 'clothes#update_deside', as: 'deside_push'
  get '/home',          to: redirect('/')

  resources :users,       only: %i[new create show edit update destroy]
  resources :clothes,     only: %i[index new create show edit update update_deside destroy]
  resources :cloth_types, only: %i[index new create destroy]
  resources :outfit_selection_rules, as: 'rules', path: 'rules',
                                     only: %i[index show new create destroy]
  resources :outfit_logs, only: %i[index new create show]

  root 'static_pages#home'
end

app/controllers/cloth_types_controller.rb
class ClothTypesController < ApplicationController
  before_action :require_login, only: %i[index new create destroy]
  before_action :set_cloth_groups, only: %i[new create]
  rescue_from ActiveRecord::RecordNotFound, with: :cloth_type_not_found

  def index
    @cloth_types = ClothType.includes(:cloth_group).all
  end

  def new
    @cloth_type = ClothType.new
  end

  def create
    @cloth_type = ClothType.new(cloth_type_create_params)
    if @cloth_type.save
      redirect_with_notice(I18n.t('flash.cloth_types.create_success'), cloth_types_url)
    else
      render_with_alert(I18n.t('flash.cloth_types.create_failure'), :new)
    end
  end

  def destroy
    @cloth_type = ClothType.find(params[:id])
    @cloth_type.destroy
    redirect_with_notice(I18n.t('flash.cloth_types.destroy_success'), cloth_type_url)
  end

  private

  def cloth_type_create_params
    params.require(:cloth_type).permit(:name, :cloth_group_id)
  end

  def set_cloth_groups
    @cloth_groups = ClothGroup.all
  end

  def cloth_type_not_found
    redirect_with_alert(I18n.t('flash.cloth_types.not_found'), cloth_url)
  end
end

app/views/cloth_types/index.html.erb
<% provide(:title, "cloth types") %>
<%= render 'layouts/flash_messages' %>

<h1>服の分類とグループ一覧</h1>
<p>・服にはそれぞれ分類（Tシャツ、ジーンズなど）が設定できます。</p>
<p>・分類１つにつき１種類のグループに属しており、<strong>服を選択するロジックには分類ではなくグループを使用します。</strong></p>
<p>例：初期状態の「Tシャツ」と「半袖Yシャツ」は別の分類ですが、「半袖（外）」という同じグループに属しています。</p>
<p class="alert-message">※分類を削除すると、その分類に属する服がすべて削除されます</p>

<div>
  <%= link_to "●服の分類を追加する", new_cloth_type_path %>
</div>

<table class="cloth_types-view">
  <thead>
    <tr>
      <th>分類名</th>
      <th>グループ名</th>
      <th>説明</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @cloth_types.each do |cloth_type| %>
      <tr>
        <td><%= cloth_type.name %></td>
        <td><%= cloth_type.cloth_group.name %></td>
        <td><%= cloth_type.cloth_group.description %></td>
        <td><%= general_delete_button("削除", cloth_type_path(cloth_type)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= back_link_to(closet_path) %>
</div>

app/views/cloth_types/new.html.erb
<% provide(:title, "add cloth type") %>
<%= render 'layouts/flash_messages' %>
<h1>服の分類を追加する</h1>

<%= form_with(model: @cloth_type, 
              local: true,
              html: { class: "form-container" }) do |form| %>

  <ul>
    <li>
      <%= form.label :name, "新しい分類名" %>
      <%= form.text_field :name %>
    </li>
    <li>
      <%= form.label :cloth_group_id, "グループ" %>
      <%= form.collection_select :cloth_group_id, @cloth_groups, :id, :name, prompt: "グループを選択してください" %>
    </li>
    <li>
      <%= form.submit "登録" %>
    </li>
  </ul>
<% end %>

<%= back_link_to(cloth_types_path) %>